name: planner
description: Planner, tracker, diary, and a habit maker.

publish_to: 'none'

version: 0.0.38-alpha

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: '>=0.5.8 <2.0.0'
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.13.7
  firebase_analytics: ^5.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Bold.ttf