name: tasker
description: Tasker, tracker, diary, and a habit maker.

publish_to: 'none'

version: 0.1.0-alpha.160

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^1.0.3
  firebase_auth: ^1.0.3
  google_sign_in: ^5.0.1
  cloud_firestore: ^1.0.4
  firebase_analytics: ^8.0.0-dev.2

  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  path_provider: ^2.0.1
  hive: ^2.0.2

  slikker_kit: #^1.0.4
    path: "../slikker_kit/"  

dev_dependencies:
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  ios: true
  android: true
  image_path: 'assets/app_icon.png'
  adaptive_icon_foreground: 'assets/app_icon_foreground.png'
  adaptive_icon_background: "#7373FF"

flutter:
  uses-material-design: true
  fonts:
  - family:  AppIcons
    fonts:
      - asset: fonts/AppIcons.ttf    

  - family: Manrope
    fonts:
      - asset: fonts/Manrope-Bold.ttf