name: planner
description: Planner, tracker, diary, and a habit maker.

publish_to: 'none'

version: 0.0.104-alpha

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0
  google_sign_in: ^4.5.3
  cloud_firestore: ^0.14.0
  firebase_analytics: ^6.0.0
  flutter_staggered_grid_view: ^0.3.2
  slikker_ripple: 
    git:
      url: git://github.com/AlexBesida/slikker_ripple.git
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  path_provider: ^1.6.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Bold.ttf